Section "Device"
    Identifier  "Rockchip Graphics"
    Driver      "modesetting"

    Option      "AccelMethod"    "glamor"
    Option      "NoEDID"         "true"
    Option      "UseGammaLUT"    "true"
EndSection

Section "Screen"
    Identifier  "Default Screen"
    Device      "Rockchip Graphics"
    Monitor     "Default Monitor"
EndSection

Section "Monitor"
    Identifier  "Default Monitor"
EndSection
